name = "MAGEMinEnsemble"
uuid = "d0dcaf60-8820-4817-989b-13fe885218e4"
authors = "Felix Boschetty <felix.boschetty@manchester.ac.uk>"
repo = "https://github.com/fboschetty/MAGEMinEnsemble.git"
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MAGEMin_C = "e5d170eb-415a-4524-987b-12f1bce1ddab"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.117"
FileIO = "1.16.6"
IterTools = "1.10.0"
MAGEMin_C = "1.7.6"
OrderedCollections = "1.8.0"
Test = "1.11.0"
